.TH SHSS\-RESOLVE\-INLINE 1 "2026-08-31" "shss 0.2.0" "Commandes utilisateur"
.SH NOM
shss\-resolve\-inline \- resolution ponctuelle d'une balise #@ ... @# (usage interne)
.SH SYNOPSIS
.B shss\-resolve\-inline
\fILIGNE\fR \fIPOSITION_CURSEUR\fR
.SH DESCRIPTION
Outil interne appelé par
.I /opt/shss/shell\-integration/shss.bash
(le raccourci \fBCtrl\-G\fR) pour résoudre, dans une ligne de bash donnée
en argument, la balise la plus proche de la position de curseur donnée.
Affiche la nouvelle ligne puis la nouvelle position du curseur, une par
ligne, sur la sortie standard.
.PP
N'est pas destiné à être appelé directement par un utilisateur.
.SH VOIR AUSSI
.BR shss (1)
